/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:070848dd-acda-4c23-be96-d77937662791",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_daodrWx9s",
    "aws_user_pools_web_client_id": "390qh73kpbv1fva71ce672mmcf",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "collection-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "collectionAPI",
            "endpoint": "https://eam4w0jakg.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
